Added v0.0.5

diff --git a/cmd/cronjobs b/cmd/cronjobs
--- a/cmd/cronjobs
+++ b/cmd/cronjobs
@@ -1,33 +1,39 @@
 #!/bin/bash
 
-# Define configuration file path
-source "configuration/garudrecon.cfg"
-PRINTBANNER
+# Default config file path
+CONFIG_PATH="configuration/garudrecon.cfg"
 
-# Check root user
-AREUROOTUSER
+TARGET=""
 
 # Help function
 function show_help() {
   cat <<EOF
+This command utilizes a web scraping approach to collect subdomains of the specified domain.
+
 Usage:
-  cmd/cronjobs -d <domain> -f <function>
+  garudrecon cronjobs [flags]
 
 Flags:
-  -d, --domain     Domain to monitor
-  -f, --function   Function to run (e.g. MONITOR_SUBDOMAIN)
-  -h, --help       Show this help message
+  -d, --domain			Domain to monitor
+  -f, --function		Function to run (e.g. MONITOR_SUBDOMAIN)
+  -h, --help			help for cronjobs
 
 Example:
-  cmd/cronjobs -d domain.com -f MONITOR_SUBDOMAIN
-  cmd/cronjobs -d domain.com -f MONITOR_PORTS
-  cmd/cronjobs -d domain.com -f MONITOR_ALIVESUBD
-  cmd/cronjobs -d domain.com -f MONITOR_JS
-  cmd/cronjobs -d domain.com -f MONITOR_JSLEAKS
+  garudrecon cronjobs -d domain.com -f MONITOR_SUBDOMAIN
+  garudrecon cronjobs -d domain.com -f MONITOR_PORTS
+  garudrecon cronjobs -d domain.com -f MONITOR_ALIVESUBD
+  garudrecon cronjobs -d domain.com -f MONITOR_JS
+  garudrecon cronjobs -d domain.com -f MONITOR_JSLEAKS
 EOF
 }
 
-# Parse flags
+# Check if no args
+if [[ $# -eq 0 ]]; then
+  show_help
+  exit 0
+fi
+
+# Parse arguments
 while [[ "$#" -gt 0 ]]; do
   case "$1" in
     -d|--domain)
@@ -38,12 +44,16 @@ while [[ "$#" -gt 0 ]]; do
       FUNC="$2"
       shift 2
       ;;
+    -config|--config)
+      CONFIG_PATH="$2"
+      shift 2
+      ;;
     -h|--help)
       show_help
       exit 0
       ;;
     *)
-      echo "Unknown flag: $1"
+      echo "Unknown option: $1"
       exit 1
       ;;
   esac
@@ -51,16 +61,89 @@ done
 
 # Escape dots in domain for regex
 ESCAPED_TARGET=$(echo "$TARGET" | sed 's/\./\\./g')
+
+if [[ -z "$TARGET" ]]; then
+    echo "Error: Target domain is required. Use -d <domain>"
+    exit 1
+fi
+
+# Load configuration
+if [[ -f "$CONFIG_PATH" ]]; then
+    source "$CONFIG_PATH"
+else
+    echo "Error: Configuration file '$CONFIG_PATH' not found."
+    exit 1
+fi
+
+PRINTBANNER
+
+# Check root user
+AREUROOTUSER
+
+# Subdirectories within cronjobscan
+CRONJOBS_SUBDOMAINDIR="cronjobscan/subdomain"
+CRONJOBS_PORTSIR="cronjobscan/ports"
+CRONJOBS_ALIVE_SUBDOMAINDIR="cronjobscan/alivesubdomain"
+CRONJOBS_JSDIR="cronjobscan/javascript"
+CRONJOBS_JSLEAKSDIR="cronjobscan/javascriptleaks"
+
+# Creating directories
 mkdir -p "$CRONJOBS_SUBDOMAINDIR"
 mkdir -p "$CRONJOBS_PORTSIR"
 mkdir -p "$CRONJOBS_ALIVE_SUBDOMAINDIR"
 mkdir -p "$CRONJOBS_JSDIR"
 mkdir -p "$CRONJOBS_JSLEAKSDIR"
 
+# Function to handle CLEANUP on Ctrl+C
+CLEANUP(){
+    if [[ -n "$SPINNER_PID" ]]; then
+        kill "$SPINNER_PID" 2>/dev/null
+    fi
+    exit 1
+}
+trap CLEANUP SIGINT
+
+START_SPINNER(){
+    processing="${1}"
+    START_TIME=$(date +%s)
+    BRAILLE_STYLE_SPINNER_CHARS=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
+    # SLASH_SPINNER_CHARS=("/" "-" "\\" "|")
+    # ARC_SPINNER_CHARS=("◐" "◓" "◑" "◒")
+    # CLASSIC_DOTS_SPINNER_CHARS=("⠂" "⠒" "⠐" "⠰" "⠴" "⠦" "⠖" "⠒")
+    # ARROW_SPINNER_CHARS=("←" "↖" "↑" "↗" "→" "↘" "↓" "↙")
+    # BOX_SPINNER_CHARS=("▖" "▘" "▝" "▗")
+    # QUARTERS_SPINNER_CHARS=("◴" "◷" "◶" "◵")
+    # CLOCK_SPINNER_CHARS=("🕛" "🕐" "🕑" "🕒" "🕓" "🕔" "🕕" "🕖" "🕗" "🕘" "🕙" "🕚")
+    # EMOJI_SPINNER_CHARS=("🌑" "🌒" "🌓" "🌔" "🌕" "🌖" "🌗" "🌘")
+    # TRAIL_SPINNER_CHARS=("⠁" "⠂" "⠄" "⠂")
+
+    while true; do
+    	ELAPSED=$(( $(date +%s) - START_TIME ))
+        for char in "${BRAILLE_STYLE_SPINNER_CHARS[@]}"; do
+            printf "${YELLOW}[${char}]${RESET} ${processing} ${CYAN}(${ELAPSED} seconds)${RESET} 🔎"
+            printf "                                    \r"
+            sleep 0.05
+        done
+    done &
+    SPINNER_PID=$!
+}
+
+STOP_SPINNER(){
+    kill "${SPINNER_PID}" 2>/dev/null
+    TIME=$(( $(date +%s) - START_TIME ))
+    return $TIME
+}
+
+echo -e "Using $CONFIG_PATH"
+
+
 # Passive Subdomain Enumeration
 MONITOR_SUBDOMAIN(){
-	if [[ ! -f "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" ]]; then
-	    curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
+	echo -e "Saving file in ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs"
+
+	START_SPINNER "${BGREEN}MONITOR_SUBDOMAIN${RESET}"
+	if [[ ! -s "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" ]]; then
+	  curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
 		# subfinder -duc -silent -d ${TARGET} -all -config ~/.config/subfinder/config.yaml -pc ~/.config/subfinder/provider-config.yaml -max-time ${SUBFINDER_ENUM_TIMEOUT} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
 		# amass enum -nocolor -nolocaldb -passive -norecursive -noalts -d ${TARGET} -config ~/.config/amass/config.ini -timeout ${AMASS_ENUM_TIMEOUT} 2>/dev/null | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
 		# echo ${TARGET} | subdog -silent -tools all | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
@@ -75,7 +158,7 @@ MONITOR_SUBDOMAIN(){
 		# echo ${TARGET} | haktrails subdomains | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
 		# echo ${TARGET} | haktrailsfree -silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t -q ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs
 	else
-	    curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
+	  curl -s "https://raw.githubusercontent.com/rix4uni/BugBountyData/refs/heads/main/data/${TARGET}.txt" | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 		# subfinder -duc -silent -d ${TARGET} -all -config ~/.config/subfinder/config.yaml -pc ~/.config/subfinder/provider-config.yaml -max-time ${SUBFINDER_ENUM_TIMEOUT} | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 		# amass enum -nocolor -nolocaldb -passive -norecursive -noalts -d ${TARGET} -config ~/.config/amass/config.ini -timeout ${AMASS_ENUM_TIMEOUT} 2>/dev/null | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 		# echo ${TARGET} | subdog -silent -tools all | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
@@ -90,48 +173,76 @@ MONITOR_SUBDOMAIN(){
 		# echo ${TARGET} | haktrails subdomains | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 		# echo ${TARGET} | haktrailsfree -silent | eval ${SUBDOMAIN_FILTER} | grep -aE "^(.*\.)?$ESCAPED_TARGET$" | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | unew -el -i -t ${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 	fi
+
+	STOP_SPINNER
+	# echo -e "${BGREEN}[+] MONITOR_SUBDOMAIN${RESET}: All subdomains: $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0), New subdomains: $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0), Time taken: ${TIME} seconds"
+	echo -e "${BGREEN}[+] MONITOR_SUBDOMAIN${RESET}\n  ├─ All subdomains : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0)\n  ├─ New subdomains : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0)\n  └─ Time taken     : ${TIME} seconds"
 }
 
 
 # Port Scanning
 MONITOR_PORTS(){
-	if [[ ! -f "${CRONJOBS_PORTSIR}/${TARGET}.naabu" ]]; then
+	START_SPINNER "${BGREEN}MONITOR_PORTS${RESET}"
+
+	echo -e "Saving file in ${CRONJOBS_PORTSIR}/${TARGET}.naabu"
+	if [[ ! -s "${CRONJOBS_PORTSIR}/${TARGET}.naabu" ]]; then
 	    cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | naabu -duc -silent -c ${NAABU_THREADS} -rate ${NAABU_RATELIMIT} -timeout ${NAABU_TIMEOUT} -retries ${NAABU_RETRIES} -top-ports 1000 2>/dev/null | unew -ef -el -i -t -q ${CRONJOBS_PORTSIR}/${TARGET}.naabu
 	else
 		cat ${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs | naabu -duc -silent -c ${NAABU_THREADS} -rate ${NAABU_RATELIMIT} -timeout ${NAABU_TIMEOUT} -retries ${NAABU_RETRIES} -top-ports 1000 2>/dev/null | unew -ef -el -i -t ${CRONJOBS_PORTSIR}/${TARGET}.naabu | unew -ef -el -i -t ${CRONJOBS_PORTSIR}/${TARGET}-new.naabu | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 	fi
+
+	STOP_SPINNER
+	echo -e "${BGREEN}[+] MONITOR_PORTS${RESET}\n  ├─ All ports      : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0)\n  ├─ New ports      : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0)\n  └─ Time taken     : ${TIME} seconds"
 }
 
 
 # Alive Subdomain Scanning
 MONITOR_ALIVESUBD(){
-	if [[ ! -f "${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs" ]]; then
+	START_SPINNER "${BGREEN}MONITOR_ALIVESUBD${RESET}"
+
+	echo -e "Saving file in ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs"
+	if [[ ! -s "${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs" ]]; then
 	    cat ${CRONJOBS_PORTSIR}/${TARGET}.naabu | httpx -duc -silent -nc -sc -title -td -cl -t ${HTTPX_THREADS} | unew -ef -el -i -t -q ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs
 	else
 		cat ${CRONJOBS_PORTSIR}/${TARGET}.naabu | httpx -duc -silent -nc -sc -title -td -cl -t ${HTTPX_THREADS} | unew -ef -el -i -t ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | unew -ef -el -i -t ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}-new.alivesubs | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 	fi
+
+	STOP_SPINNER
+	echo -e "${BGREEN}[+] MONITOR_ALIVESUBD${RESET}\n  ├─ All alive subdomains : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0)\n  ├─ New alive subdomains : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0)\n  └─ Time taken           : ${TIME} seconds"
 }
 
 
 # Javascript Scanning
 MONITOR_JS(){
-	if [[ ! -f "${CRONJOBS_JSDIR}/${TARGET}.js" ]]; then
+	START_SPINNER "${BGREEN}MONITOR_JS${RESET}"
+
+	echo -e "Saving file in ${CRONJOBS_JSDIR}/${TARGET}.js"
+	if [[ ! -s "${CRONJOBS_JSDIR}/${TARGET}.js" ]]; then
 	    cat ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | awk '{print $1}' | subjs | grep -aE "(https?://$TARGET(:[0-9]+)?(/)|\.$TARGET[:/])" | unew -ef -el -i -t -q ${CRONJOBS_JSDIR}/${TARGET}.js
 	else
 		cat ${CRONJOBS_ALIVE_SUBDOMAINDIR}/${TARGET}.alivesubs | awk '{print $1}' | subjs | grep -aE "(https?://$TARGET(:[0-9]+)?(/)|\.$TARGET[:/])" | unew -ef -el -i -t ${CRONJOBS_JSDIR}/${TARGET}.js | unew -ef -el -i -t ${CRONJOBS_JSDIR}/${TARGET}-new.js | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 	fi
+
+	STOP_SPINNER
+	echo -e "${BGREEN}[+] MONITOR_JS${RESET}\n  ├─ All js         : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0)\n  ├─ New js         : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0)\n  └─ Time taken     : ${TIME} seconds"
 }
 
 
 # Javascript Leaks Scanning
 MONITOR_JSLEAKS(){
-	if [[ ! -f "${CRONJOBS_JSDIR}/${TARGET}.jsleaks" ]]; then
+	START_SPINNER "${BGREEN}MONITOR_JSLEAKS${RESET}"
+
+	echo -e "Saving file in ${CRONJOBS_JSDIR}/${TARGET}.jsleaks"
+	if [[ ! -s "${CRONJOBS_JSDIR}/${TARGET}.jsleaks" ]]; then
 	    cat ${CRONJOBS_JSDIR}/${TARGET}.js | egrep -av "\.json" | grep -a "\.js" | linkinspector -silent -nc -mt "application/javascript" | awk '{print $1}' | unew -ef -el -i -t -q ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks
 	    cat ${CRONJOBS_JSDIR}/${TARGET}.js | nuclei -duc -silent -nc -t ~/nuclei-templates/exposures/ | unew -ef -el -i -t -q ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks
 	else
 		cat ${CRONJOBS_JSDIR}/${TARGET}.js | egrep -av "\.json" | grep -a "\.js" | linkinspector -silent -nc -mt "application/javascript" | awk '{print $1}' | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}-new.jsleaks | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 		cat ${CRONJOBS_JSDIR}/${TARGET}.js | nuclei -duc -silent -nc -t ~/nuclei-templates/exposures/ | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}.jsleaks | unew -ef -el -i -t ${CRONJOBS_JSLEAKSDIR}/${TARGET}-new.jsleaks | notify -silent -duc -bulk -id subdomain-moniter &>/dev/null
 	fi
+
+	STOP_SPINNER
+	echo -e "${BGREEN}[+] MONITOR_JSLEAKS${RESET}\n  ├─ All jsleaks    : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}.subs" || echo 0)\n  ├─ New jsleaks    : $(wc -l 2>/dev/null < "${CRONJOBS_SUBDOMAINDIR}/${TARGET}-new.subs" || echo 0)\n  └─ Time taken     : ${TIME} seconds"
 }
 
 
diff --git a/cmd/mediumscope b/cmd/mediumscope
--- a/cmd/mediumscope
+++ b/cmd/mediumscope
@@ -1,11 +1,187 @@
 #!/bin/bash
 
-# Define configuration file path
-source "configuration/garudrecon.cfg"
+# Default config file path
+CONFIG_PATH="configuration/garudrecon.cfg"
+
+TARGET=""
+
+EXCLUDE_FUNCS=()
+RECON_XSS=false
+RECON_SQLI=false
+RECON_LFI=false
+RECON_SUBTAKEOVER=false
+RECON_RCE=false
+RECON_IIS=false
+
+# Help function
+function show_help() {
+  cat <<EOF
+This command utilizes a web scraping approach to collect subdomains of the specified domain.
+
+Usage:
+  garudrecon mediumscope [flags]
+
+Flags:
+  -rx, --recon-xss			Run full recon with XSS checks"
+  -rs, --recon-sqli			Run full recon with SQLi checks"
+  -rl, --recon-lfi			Run full recon with LFI checks"
+  -rst, --recon-subtakeover		Run full recon with Subdomain Takeover checks"
+  -rr, --recon-rce 	   		Run full recon with RCE checks"
+  -ri, --recon-iis 	   		Run full recon with IIS checks"
+  -h, --help				help for mediumscope
+
+Example:
+# Full recon
+  garudrecon mediumscope -d dell.com
+
+# Recon with XSS only
+  garudrecon mediumscope -d dell.com -rx
+
+# Recon with SQLi only
+  garudrecon mediumscope -d dell.com -rs
+
+# Exclude functions manually
+  garudrecon mediumscope -d dell.com -ef "SUBFINDER,AMASS"
+
+# Combined
+  garudrecon mediumscope -d dell.com -rx -ef "AMASS"
+EOF
+}
+
+# Check if no args
+if [[ $# -eq 0 ]]; then
+  show_help
+  exit 0
+fi
+
+# Parse arguments
+while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+        -d|--domain)
+            TARGET="$2"
+            shift 2
+            ;;
+        -ef|--exclude-functions)
+            IFS=',' read -ra raw_funcs <<< "$2"
+            EXCLUDE_FUNCS=()
+            for func in "${raw_funcs[@]}"; do
+                trimmed_func=$(echo "$func" | xargs)
+                EXCLUDE_FUNCS+=("$trimmed_func")
+            done
+            shift 2
+            ;;
+	    -rx|--recon-xss)
+	        RECON_XSS=true
+	        shift
+	        ;;
+	    -rs|--recon-sqli)
+	        RECON_SQLI=true
+	        shift
+	        ;;
+	    -rl|--recon-lfi)
+	        RECON_LFI=true
+	        shift
+	        ;;
+	    -rst|--recon-subtakeover)
+	        RECON_SUBTAKEOVER=true
+	        shift
+	        ;;
+	    -rr|--recon-rce)
+	        RECON_RCE=true
+	        shift
+	        ;;
+	    -ri|--recon-iis)
+	        RECON_IIS=true
+	        shift
+	        ;;
+        -config|--config)
+            CONFIG_PATH="$2"
+            shift 2
+            ;;
+        -h|--help)
+	        show_help
+	        exit 0
+	        ;;
+        *)
+            echo "Unknown option: $1"
+            exit 1
+            ;;
+    esac
+done
+
+# Escape dots in domain for regex
+ESCAPED_TARGET=$(echo "$TARGET" | sed 's/\./\\./g')
+
+if [[ -z "$TARGET" ]]; then
+    echo "Error: Target domain is required. Use -d <domain>"
+    exit 1
+fi
+
+# Load configuration
+if [[ -f "$CONFIG_PATH" ]]; then
+    source "$CONFIG_PATH"
+else
+    echo "Error: Configuration file '$CONFIG_PATH' not found."
+    exit 1
+fi
+
 PRINTBANNER
 
 # Check root user
 AREUROOTUSER
+
+# Base directory
+BASEDIR="scans"
+
+# Function to generate a unique directory name
+generate_unique_dir(){
+    local dir_path="$BASEDIR/$TARGET"
+    local counter=1
+    
+    while [ -d "$dir_path" ]; do
+        dir_path="$BASEDIR/${TARGET}_$counter"
+        ((counter++))
+    done
+
+    echo "$dir_path"
+}
+
+# Generate unique domain directory
+UNIQUEDOMAINDIR=$(generate_unique_dir)
+TMPDIR="$UNIQUEDOMAINDIR/.tmp"
+
+# Subdirectories within .tmp
+SUBDOMAINDIR="$TMPDIR/subdomain"
+FFUFBRUTE="$TMPDIR/ffufbrute"
+FAVICON_HASH="$TMPDIR/favicon_hash"
+SCREENSHOTS="$TMPDIR/screenshots"
+URLSDIR="$TMPDIR/urls"
+VULNDIR="$TMPDIR/vuln"
+GITHUB_ENDPOINTSDIR="$URLSDIR/github_endpoints"
+CRAWLEYDIR="$URLSDIR/crawley"
+CARIDDIDIR="$URLSDIR/cariddi"
+XCRAWL3RDIR="$URLSDIR/xcrawl3r"
+GOLINKFINDERDIR="$URLSDIR/GoLinkFinder"
+AUTOMATED_GOOGLE_DORKINGDIR="$URLSDIR/dorks_hunter"
+SOURCEMAPPERDIR="$URLSDIR/sourcemapper"
+FTPDIR="$VULNDIR/ftp"
+IISIDR="$VULNDIR/iis"
+DOTGITDIR="$VULNDIR/dotgit"
+PDFTOTEXTDIR="$VULNDIR/pdftotext"
+
+# Root-level directories in UNIQUEDOMAINDIR
+ROOT_SUBDOMAINDIR="$UNIQUEDOMAINDIR/subdomain"
+ROOT_URLSDIR="$UNIQUEDOMAINDIR/urls"
+ROOT_EMAILSDIR="$UNIQUEDOMAINDIR/emails"
+ROOT_VULNDIR="$UNIQUEDOMAINDIR/vuln"
+ROOT_LOGS="$UNIQUEDOMAINDIR/logs"
+ROOT_RESUME="$UNIQUEDOMAINDIR/resume"
+ROOT_INPUTFILES="$UNIQUEDOMAINDIR/inputfiles"
+ROOT_WORDLISTDIR="$UNIQUEDOMAINDIR/wordlist"
+
+ERRORLOGFILE="$ROOT_LOGS/error.log"
+SUMMARYLOGFILE="$ROOT_LOGS/summary.logs"
+
 
 # Creating directories
 # Subdirectories within .tmp
@@ -45,6 +221,26 @@ touch "$ROOT_INPUTFILES/inscope.txt"
 touch "$ROOT_INPUTFILES/outofscope.txt"
 touch "$ROOT_INPUTFILES/crunchbase.txt"
 touch "$ROOT_INPUTFILES/manual_google_dorking.txt"
+
+# Utility function to check if a function is excluded
+is_excluded() {
+    local func="$1"
+    for excluded in "${EXCLUDE_FUNCS[@]}"; do
+        if [[ "$excluded" == "$func" ]]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+run() {
+    local func="$1"
+    if is_excluded "$func"; then
+        echo -e "${YELLOW}[~] $func${RESET}: 0, ${TIME} seconds" | unew -a $SUMMARYLOGFILE
+    else
+        $func
+    fi
+}
 
 # Function to handle CLEANUP on Ctrl+C
 CLEANUP(){
@@ -89,6 +285,7 @@ STOP_SPINNER(){
 STARTED_AT=$(date +"%d-%m-%Y_%H:%M:%S")
 START_EPOCH=$(date +%s)
 
+echo -e "Using $CONFIG_PATH"
 echo -e "Saving all files in $UNIQUEDOMAINDIR"
 
 
@@ -2397,203 +2594,373 @@ DELETE_TMPDIR(){
 }
 
 
-# Subdomain Enumeration
-BUGBOUNTYDATA
-SUBFINDER
-AMASS
-SUBDOG
-FINDOMAIN
-CHAOS
-GITHUB_SUBDOMAINS
-# BBOT # Temporary
-ONEFORALL
-SHOSUBGO
-ASSETFINDER
-HAKTRAILS
-# HAKTRAILSFREE
+RECON(){
+	# Subdomain Enumeration
+	run "BUGBOUNTYDATA"
+	run "SUBFINDER"
+	run "AMASS"
+	run "SUBDOG"
+	run "FINDOMAIN"
+	run "CHAOS"
+	run "GITHUB_SUBDOMAINS"
+	# run "BBOT"
+	run "ONEFORALL"
+	run "SHOSUBGO"
+	run "ASSETFINDER"
+	run "HAKTRAILS"
+	# run "HAKTRAILSFREE"
 
 
-# Certificate Transperency
-CERO
-CERTINFO
-CSPRECON
-CSPFINDER
-ALLSUBDOMAIN
-# RECURSIVESUBENUM
+	# Certificate Transperency
+	run "CERO"
+	run "CERTINFO"
+	run "CSPRECON"
+	run "CSPFINDER"
+	run "ALLSUBDOMAIN"
+	# run "RECURSIVESUBENUM"
 
 
-# Subdomain Permutations
-# ALTDNS
-# PUREDNS
-# ALTERX
-# GOTATOR
-# DNSGEN
-# GOALTDNS
-# RIPGEN
-# DNSCEWL
-# ALLSUBDOMAINPERMUTATIONS
+	# Subdomain Permutations
+	# run "ALTDNS"
+	# run "PUREDNS"
+	# run "ALTERX"
+	# run "GOTATOR"
+	# run "DNSGEN"
+	# run "GOALTDNS"
+	# run "RIPGEN"
+	# run "DNSCEWL"
+	# run "ALLSUBDOMAINPERMUTATIONS"
 
 
-# Subdomain Resolving
-# PUREDNS
-# SHUFFLEDNS
-# MASSDNS
+	# Subdomain Resolving
+	# run "PUREDNS"
+	# run "SHUFFLEDNS"
+	# run "MASSDNS"
 
 
-# Subdomain DNS Enumeration
-# DNSX
+	# Subdomain DNS Enumeration
+	# run "DNSX"
 
 
-# Cloud Recon
-KAEFERJAEGER
+	# Cloud Recon
+	run "KAEFERJAEGER"
 
 
-# Port Scanning
-NAABU
-# MASSCAN
-# RUSTSCAN
-# NMAP
+	# Port Scanning
+	run "NAABU"
+	# run "MASSCAN"
+	# run "RUSTSCAN"
+	# run "NMAP"
 
 
-# Subdomain Probing
-HTTPX
+	# Subdomain Probing
+	run "HTTPX"
 
 
-# Subdomain Bruteforcing
-# FFUFBRUTE # Temporary
+	# Subdomain Bruteforcing
+	# run "FFUFBRUTE"
 
 
-# VHOST Dicovery
-# FFUFVHOST
+	# VHOST Dicovery
+	# run "FFUFVHOST"
 
 
-# Favicon Lookup
-FAVINFO
-FAVIRECON
+	# Favicon Lookup
+	run "FAVINFO"
+	run "FAVIRECON"
 
 
-# Screenshotting
-# GOWITNESS
-# AQUATONE
-# EYEWITNESS
-# HTTPX_SS
+	# Screenshotting
+	# run "GOWITNESS"
+	# run "AQUATONE"
+	# run "EYEWITNESS"
+	# run "HTTPX_SS"
 
 
-# Directory Enumeration
-# FFUFDIRENUM
-# DIRSEARCH
-# FEROXBUSTER
-# WFUZZ
+	# Directory Enumeration
+	# run "FFUFDIRENUM"
+	# run "DIRSEARCH"
+	# run "FEROXBUSTER"
+	# run "WFUZZ"
 
 
-# Email Enumeration
-# EMAILFINDER
+	# Email Enumeration
+	# run "EMAILFINDER"
 
 
-# Url Crawling
-WAYMORE
-HAKRAWLER
-WAYBACKURLS
-KATANA
-GAU
-# GOSPIDER
-UFORALL
-URLFINDER
-GITHUB_ENDPOINTS
-XURLFIND3R
-XCRAWL3R
-CRAWLEY
-GOLINKFINDER
-# GALER # Taking too much ram need to be fixed
-# PATHFINDER
-PATHCRAWLER
-ROBOXTRACTOR
-ROBOTXT
+	# Url Crawling
+	run "WAYMORE"
+	run "HAKRAWLER"
+	run "WAYBACKURLS"
+	run "KATANA"
+	run "GAU"
+	# run "GOSPIDER"
+	run "UFORALL"
+	run "URLFINDER"
+	run "GITHUB_ENDPOINTS"
+	run "XURLFIND3R"
+	run "XCRAWL3R"
+	run "CRAWLEY"
+	run "GOLINKFINDER"
+	# run "GALER # Taking too much ram need to be fixed"
+	# run "PATHFINDER"
+	run "PATHCRAWLER"
+	run "ROBOXTRACTOR"
+	run "ROBOTXT"
 
 
-# Google Dorking
-# AUTOMATED_GOOGLE_DORKING
-# MANUAL_GOOGLE_DORKING # Temporary
+	# Google Dorking
+	# run "AUTOMATED_GOOGLE_DORKING"
+	# run "MANUAL_GOOGLE_DORKING"
 
 
-# JS Crawling
-SUBJS
-GETJS
-JSCRAWLER
-JSFINDER
-# JAVASCRIPT_DEOBFUSCATOR
-# LINKFINDER
-XNLINKFINDER
-# GETJSWORDS
-SOURCEMAPPER
-# LINX
-# JSLUICE
+	# JS Crawling
+	run "SUBJS"
+	run "GETJS"
+	run "JSCRAWLER"
+	run "JSFINDER"
+	# run "JAVASCRIPT_DEOBFUSCATOR"
+	# run "LINKFINDER"
+	run "XNLINKFINDER"
+	# run "GETJSWORDS"
+	run "SOURCEMAPPER"
+	# run "LINX"
+	# run "JSLUICE"
 
 
-# Hidden Parameter
-PARAMFINDER
-# MSARJUN # Temporary
-# X8 # Temporary
-ALLURLS
-MANUAL_ALLURLS_FILTER
+	# Hidden Parameter
+	run "PARAMFINDER"
+	# run "MSARJUN"
+	# run "X8"
+	run "ALLURLS"
+	run "MANUAL_ALLURLS_FILTER"
 
 
-# Program Based Wordlist Generator
-# CEWL
-# UNFURL
-# CUSTOM_PARAM
-# COOK
-# PYDICTOR
+	# Delete TMPDIR files
+	run "DELETE_TMPDIR"
+}
+
+# Run functions based on selected recon mode
+if [[ "$RECON_XSS" == true ]]; then
+    RECON
+    run "XSS"
+    run "SWAGGERUI"
+elif [[ "$RECON_SQLI" == true ]]; then
+    RECON
+    run "ERRORBASEDSQLI"
+	# run "TIMEBASEDSQLI"
+elif [[ "$RECON_LFI" == true ]]; then
+    RECON
+    run "LFI"
+elif [[ "$RECON_SUBTAKEOVER" == true ]]; then
+    RECON
+    run "SUBZY"
+	run "NUCLEI"
+elif [[ "$RECON_RCE" == true ]]; then
+    RECON
+    run "RCE"
+elif [[ "$RECON_IIS" == true ]]; then
+    RECON
+    run "IIS"
+else
+    # Default behavior: run all
+    # Subdomain Enumeration
+	run "BUGBOUNTYDATA"
+	run "SUBFINDER"
+	run "AMASS"
+	run "SUBDOG"
+	run "FINDOMAIN"
+	run "CHAOS"
+	run "GITHUB_SUBDOMAINS"
+	# run "BBOT"
+	run "ONEFORALL"
+	run "SHOSUBGO"
+	run "ASSETFINDER"
+	run "HAKTRAILS"
+	# run "HAKTRAILSFREE"
 
 
-# FFUF_CUSTOM_PARAM
+	# Certificate Transperency
+	run "CERO"
+	run "CERTINFO"
+	run "CSPRECON"
+	run "CSPFINDER"
+	run "ALLSUBDOMAIN"
+	# run "RECURSIVESUBENUM"
 
 
-# Subdomain Takeover
-SUBZY
-NUCLEI
+	# Subdomain Permutations
+	# run "ALTDNS"
+	# run "PUREDNS"
+	# run "ALTERX"
+	# run "GOTATOR"
+	# run "DNSGEN"
+	# run "GOALTDNS"
+	# run "RIPGEN"
+	# run "DNSCEWL"
+	# run "ALLSUBDOMAINPERMUTATIONS"
 
 
-# MX Takeover
-MXTAKEOVER
-
-# DNS takeover
-DNSTAKE
-
-# Zone Transfer
-# DIG
+	# Subdomain Resolving
+	# run "PUREDNS"
+	# run "SHUFFLEDNS"
+	# run "MASSDNS"
 
 
-# Vulnerability Scanning
-FTP
-# SSH
-VULNTECHX
-# XSS # Temporary
-ERRORBASEDSQLI
-# TIMEBASEDSQLI
-# LFI # Temporary
-RCE
-DOTGIT
-PDFTOTEXT
-# JSLEAKS
-# JSONLEAKS
-# GITHUBLEAKS
-IIS
-SWAGGERUI
-# 403_401_BYPASS
+	# Subdomain DNS Enumeration
+	# run "DNSX"
 
 
-# URLs Secrets
-# LINKINSPECTOR
+	# Cloud Recon
+	run "KAEFERJAEGER"
 
 
-# Password spraying
-# BRUTESPRAY
+	# Port Scanning
+	run "NAABU"
+	# run "MASSCAN"
+	# run "RUSTSCAN"
+	# run "NMAP"
 
 
-# Delete TMPDIR files
-DELETE_TMPDIR
+	# Subdomain Probing
+	run "HTTPX"
 
+
+	# Subdomain Bruteforcing
+	# run "FFUFBRUTE"
+
+
+	# VHOST Dicovery
+	# run "FFUFVHOST"
+
+
+	# Favicon Lookup
+	run "FAVINFO"
+	run "FAVIRECON"
+
+
+	# Screenshotting
+	# run "GOWITNESS"
+	# run "AQUATONE"
+	# run "EYEWITNESS"
+	# run "HTTPX_SS"
+
+
+	# Directory Enumeration
+	# run "FFUFDIRENUM"
+	# run "DIRSEARCH"
+	# run "FEROXBUSTER"
+	# run "WFUZZ"
+
+
+	# Email Enumeration
+	# run "EMAILFINDER"
+
+
+	# Url Crawling
+	run "WAYMORE"
+	run "HAKRAWLER"
+	run "WAYBACKURLS"
+	run "KATANA"
+	run "GAU"
+	# run "GOSPIDER"
+	run "UFORALL"
+	run "URLFINDER"
+	run "GITHUB_ENDPOINTS"
+	run "XURLFIND3R"
+	run "XCRAWL3R"
+	run "CRAWLEY"
+	run "GOLINKFINDER"
+	# run "GALER # Taking too much ram need to be fixed"
+	# run "PATHFINDER"
+	run "PATHCRAWLER"
+	run "ROBOXTRACTOR"
+	run "ROBOTXT"
+
+
+	# Google Dorking
+	# run "AUTOMATED_GOOGLE_DORKING"
+	# run "MANUAL_GOOGLE_DORKING"
+
+
+	# JS Crawling
+	run "SUBJS"
+	run "GETJS"
+	run "JSCRAWLER"
+	run "JSFINDER"
+	# run "JAVASCRIPT_DEOBFUSCATOR"
+	# run "LINKFINDER"
+	run "XNLINKFINDER"
+	# run "GETJSWORDS"
+	run "SOURCEMAPPER"
+	# run "LINX"
+	# run "JSLUICE"
+
+
+	# Hidden Parameter
+	run "PARAMFINDER"
+	# run "MSARJUN"
+	# run "X8"
+	run "ALLURLS"
+	run "MANUAL_ALLURLS_FILTER"
+
+
+	# Program Based Wordlist Generator
+	# run "CEWL"
+	# run "UNFURL"
+	# run "CUSTOM_PARAM"
+	# run "COOK"
+	# run "PYDICTOR"
+
+
+	# run "FFUF_CUSTOM_PARAM"
+
+
+	# Subdomain Takeover
+	run "SUBZY"
+	run "NUCLEI"
+
+
+	# MX Takeover
+	run "MXTAKEOVER"
+
+	# DNS takeover
+	run "DNSTAKE"
+
+	# Zone Transfer
+	# run "DIG"
+
+
+	# Vulnerability Scanning
+	run "FTP"
+	# run "SSH"
+	run "VULNTECHX"
+	# run "XSS"
+	run "ERRORBASEDSQLI"
+	# run "TIMEBASEDSQLI"
+	# run "LFI"
+	run "RCE"
+	run "DOTGIT"
+	run "PDFTOTEXT"
+	# run "JSLEAKS"
+	# run "JSONLEAKS"
+	# run "GITHUBLEAKS"
+	run "IIS"
+	run "SWAGGERUI"
+	# run "403_401_BYPASS"
+
+
+	# URLs Secrets
+	# run "LINKINSPECTOR"
+
+
+	# Password spraying
+	# run "BRUTESPRAY"
+
+
+	# Delete TMPDIR files
+	run "DELETE_TMPDIR"
+fi
 
 
 ENDED_AT=$(date +"%d-%m-%Y_%H:%M:%S")
